### ISSUE TITLE
WebP Images resolution not working in Gutenberg on wordpress.com | Modern Image Format 

### ISSUE THREAD

**Issue by tehjaymo** [WordPress/performance#1499] opened 2024-08-26 21:36 UTC
## Bug Description

I recently moved hosts returning to wordpress.com.
I've been using the Modern Image Formats plugin since release without issue. 

However, since the site move whenever I upload a new image in the editor I get an error: "This image has an empty alt attribute; its file name is G0061259-1024x768.webp"

which is weird because the plugin re-names the file with -jpg- The block should be looking for G0061259-jpg-1024x768.webp or whatever image resolution was produced. The error occurs on all file resolution sizes except 'original' which displays correctly in the editor.

All images however display correctly on the front end.

## Steps to reproduce

1. Go to wordpress.com hosted blog
2. Install the Modern Image Formats plugin
3. Upload an image in the editor
5. See error

## Screenshots

<img width="942" alt="Screenshot 2024-08-26 at 22 14 09" src="https://github.com/user-attachments/assets/c1d571f2-a616-4e0c-9379-74d12c2075db">

## Additional Context

WordPress 6.6.1
PHP 8.1
Gutenberg 19.0.0

Whatever the wordpress.com Business hosting plan standard Nginx plan setting are. 

Existing files and pages pre move have no issues. Only new uploads.

Selecting 'Outputi JPEG images in addition to the modern format' solves the issue in the editor, webp images display on the front end. 
But this isn't too sustainable long term imo.

**Comment by westonruter** [comment] 2024-08-26 23:54
Aside: On WordPress.com there is an Image CDN which should automatically serve WebP for uploaded images.

**Comment by adamsilverstein** [comment] 2024-09-09 15:24
Thanks for the bug report @tehjaymo... As @westonruter points out above, you may not need this plugin with wp.com already offering an image CDN with WebP support built in (but not AVIF afaik).

Still, I'm curious if I can reproduce, can you confirm what type of plan you are on?

Also, can you check Tools->Site Health->Info->Media and report back here what Editor/filetype support is listed?

**Comment by tehjaymo** [comment] 2024-09-09 16:11
Huh, thats weird. I've testes with the plugin turned of but CD turned on and it only seems to server resized jpgs. Anywhoos here's the info from my site health


Active editor | Photon_Subsizes_WP_Image_Editor_GD
-- | --
ImageMagick version number | Not available
ImageMagick version string | Not available
Imagick version | Not available
File uploads | Enabled
Max size of post data allowed | 2047M
Max size of an uploaded file | 2047M
Max effective file size | 2 GB
Max number of files allowed | 20
GD version | bundled (2.1.0 compatible)
GD supported file formats | GIF, JPEG, PNG, WebP, BMP, AVIF
Ghostscript version | Not available

**Comment by adamsilverstein** [comment] 2024-12-02 15:40
@tehjaymo thanks for the details. Interesting to note that wp.com is using a custom Image Editor class - `Photon_Subsizes_WP_Image_Editor_GD`.

> Aside: On WordPress.com there is an Image CDN which should automatically serve WebP for uploaded images.

Using the image CDN is probably the best advice on .com. although I don't think it supports AVIF?

Should we warn users here if we know the plugin won't work correctly?

**Comment by adamsilverstein** [comment] 2024-12-02 15:57
I tried to test this out, unfortunately wordpress.com _requires a paid account to install plugins_.

I also verified Photon still doesn't support AVIF images, although the reasoning might be out of date. I commented on the closed ticket: https://github.com/Automattic/jetpack/issues/35432

**Comment by adamsilverstein** [comment] 2024-12-02 16:01
I am closing this ticket as "wontfix" since wordpress.com is a closed platform and the source of `Photon_Subsizes_WP_Image_Editor_GD` is not available, we can't be sure why this doesn't work. Furthermore, images are served from an image CDN on wordpress.com (aka `Photon`) so this plugin shouldn't be required, instead I would encourage users to rely on Photon and work towards landing support for AVIF there.

**Closed as completed by adamsilverstein** 2024-12-02 16:01 UTC
Labels: [Type] Bug, [Plugin] Modern Image Formats
