### ISSUE TITLE
Performance Lab (version 3.0.0) update crashed site

### ISSUE THREAD

**Issue by brucefryer** [WordPress/performance#1180] opened 2024-04-24 23:26 UTC
## Bug Description

1. Got email and website would not load and could not login to Admin. Used Recovery Mode login and disabled plugin.
2. Howdy!

WordPress has a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.

In this case, WordPress caught an error with one of your plugins, Performance Lab.

First, visit your website (https://fryergroup.com/top/) and check for any visible issues. Next, visit the page where the error was caught (https://fryergroup.com/top/top/wp-login.php) and check for any visible issues.

Please contact your host for assistance with investigating this issue further.

If your site appears broken and you can't access your dashboard normally, WordPress now has a special "recovery mode". This lets you safely login to your dashboard and investigate further.

https://fryergroup.com/top/xxxxxxxxxxxxxxx

To keep your site safe, this link will expire in 1 day. Don't worry about that, though: a new link will be emailed to you if the error occurs again after it expires.

When seeking help with this issue, you may be asked for some of the following information:
WordPress version 6.5.2
Active theme: Visual Composer Starter (version 3.3)
Current plugin: Performance Lab (version 3.0.0)
PHP version 7.4.33

Error Details
=============
An error of type E_COMPILE_ERROR was caused in line 14 of the file /home/fryergro/public_html/top/wp-content/plugins/performance-lab/includes/server-timing/class-perflab-server-timing-metric.php. Error message: Cannot declare class Perflab_Server_Timing_Metric, because the name is already in use

## Steps to reproduce

3. Click on '....'
4. Scroll down to '....'
5. See error

## Screenshots

![error](https://github.com/WordPress/performance/assets/29104611/f3618190-64d2-4ca2-bb7b-bfd33bed2b6e)

## Additional Context

 - PHP Version: 7.4.33
 - OS: [e.g. iOS] MacOS 14.4.1 (23E224)
 - Browser: [e.g. chrome, safari] Firefox 125.0.1 (64-bit
 - Plugin Version: [e.g. 22] Performance Lab (version 3.0.0)
 - Device: [e.g. iPhone6] MacBook Air Retina, 13-inch, 2019

**Comment by westonruter** [comment] 2024-04-25 01:07
Hi there. This was reported already in another issue: #1150

However, we have not been able to reproduce the issue. It seems due to a problem in WordPress's plugin upgrader system. 

Please see that issue for more details. I'm closing this as a duplicate.

**Closed as not planned by westonruter** 2024-04-25 01:07 UTC
Labels: [Type] Bug
