### ISSUE TITLE
Allow flush runtime cache to be flushed

### ISSUE THREAD

**Issue by tillkruss** [WordPress/performance#81] opened 2022-01-04 19:55 UTC
Allowing users to flush the runtime (in-memory) cache, without flushing the entire persistent cache is an often requested features for app running long processes, such as Action Scheduler or WP-CLI.

- https://github.com/woocommerce/action-scheduler/issues/790
- https://github.com/WordPress/performance/issues/36#issuecomment-1005025385

I'm not sure about the naming here, since we need to distinguish between PHP memory and the persistent cache backend.

```php
/**
 * Removes all cache items from the runtime memory,
 * without flushing the persistent cache storage.
 *
 * @see WP_Object_Cache::flush_runtime()
 * @global WP_Object_Cache $wp_object_cache Object cache global instance.
 *
 * @return bool True on success, false on failure.
 */
function wp_cache_flush_runtime() {
	global $wp_object_cache;

	return $wp_object_cache->flush_runtime();
}
```

**Comment by JanThiel** [comment] 2022-01-12 16:41
To add some reference to core parts currently suffer from this:
All WP core APIs using `get_metadata_raw` including but not limited to `get_post_meta`, `get_user_meta` et cetera.

Very obvious and impacting the WP user experience are the effects on `WP_User_Meta_Session_Tokens`. Any concurrency issues / stale runtime caches lead to random logouts and session terminations. We are still debugging this at the moment but are quite certain that Object Cache concurrency issues are the root cause for this on our platform.

**Comment by spacedmonkey** [comment] 2022-01-20 11:16
The XWP performance team has been working on a patch for this. @pbearne has been taking the lead on this. If you want to see his progress, you can see his PR at https://github.com/xwp/wordpress-develop/pull/4.

**Comment by eclarke1** [comment] 2022-01-20 11:57
@spacedmonkey thanks, with this in mind, do you feel this ticket should be assigned to @pbearne and moved to 'In Progress' so no-one else picks it up?

**Comment by tillkruss** [comment] 2022-01-20 17:34
@spacedmonkey: The PR you liked is related to #38 (flushing individual groups) and not this (flushing runtime caches).

This issue needs a discussion, mostly around naming.

**Comment by eclarke1** [comment] 2022-01-21 10:40
@tillkruss perhaps worth removing that 'Needs Dev' label until we have decided what the approach is here, otherwise it will show up in the links we send to the community as 'requests for development' - once the approach is agreed via a discussion, we can add the 'Needs Dev' label back to indicate to the community it's ready to go :)

**Comment by mxbclang** [comment] 2022-01-25 22:17
@tillkruss For issues labeled Needs Decision, we'd like to include a recommendation for moving forward that folks can give a thumbs up/thumbs down on, as you can see here: https://github.com/WordPress/performance/issues/96#issuecomment-1016458629. If you'd like to drop that here as a comment, I can copy it and add a voting deadline and instructions. Thanks!

**Comment by tillkruss** [comment] 2022-01-26 17:35
_Please vote for your preferred naming using the related reaction._

We currently have the `wp_cache_flush()` function, but need an additional method to only flush the current request/process cache. This is useful for long running processes like WP CLI and Action Scheduler and highly customized sites.

- 🎉 `wp_cache_flush_runtime()`
- 🚀 `wp_cache_flush_internal()`
- ❤️ `wp_cache_flush_local()`
- 👀 `wp_cache_flush_worker()`

**Comment by eclarke1** [comment] 2022-02-01 13:24
@tillkruss @bethanylang could I kindly suggest we add a 'voting deadline' to this https://github.com/WordPress/performance/issues/81#issuecomment-1022431042 
I think we agreed a 2 week voting period, so perhaps the deadline here should be **6pm GMT on February 9**, WDYT?

**Comment by mxbclang** [comment] 2022-02-01 13:31
@eclarke1 Works for me, will make a note to myself to update and "close" at 6pm GMT on February 9.

**Comment by tillkruss** [comment] 2022-02-04 17:21
See https://core.trac.wordpress.org/ticket/55080

**Comment by spacedmonkey** [comment] 2022-02-18 12:07
Merged in https://github.com/WordPress/wordpress-develop/commit/c98f4c04db13a1c3db14345db4cff116dd01bf51

**Closed as completed** 2022-02-18 12:08 UTC
Labels: [Type] Feature
