### ISSUE TITLE
Activating multiple features / plugins sequentially fails to activate some features / plugins

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/performance#1660] opened 2024-11-18 05:53 UTC
## Bug Description

Following the implementation of #1583, Performance features are now installed and activated via AJAX. However, during smoke testing, I observed issues when activating multiple features / plugins sequentially.

### Steps to Reproduce

1. Activate `Modern Image Formats`, `Embed Optimizer`, and `Web Worker Offloading` one by one.
2. Check the status on the Installed Plugins page and the Performance Features page.

### Observed Behaviour

- On the Installed Plugins page:
  - `Embed Optimizer` and its dependent `Optimization Detective` plugins are not marked as activated.
- On the Performance Features page:
  - Initially, `Embed Optimizer` appears as activated. However, after reloading the page, its state changes to Activate.

### Additional Scenario
- When activating all performance features / plugins one by one, some features remain only installed and not activated.

### Screen Recording & Screenshots:

https://github.com/user-attachments/assets/83f359ed-345d-479c-9abf-e5f779139662

![Image](https://github.com/user-attachments/assets/5d7cdbff-9a95-441b-a210-bc5fad4eec0a)
![Image](https://github.com/user-attachments/assets/787a0620-7b3a-4054-acec-032b59974adb)

**Comment by felixarntz** [comment] 2024-11-18 17:06
As the 3.6.0 release is going out today and this is not super critical, let's target this to land in an extra 3.6.1 release of Performance Lab, e.g. next week. cc @thelovekesh

**Comment by felixarntz** [comment] 2024-11-18 18:56
@mukeshpanchal27 @thelovekesh @adamsilverstein I just double-checked WordPress Core in that regard: It does not actually use AJAX for this, plugin activation via the cards is handled with a full page load. So there's nothing we can reuse from Core for this.

Therefore, I think the best approach for now would be to queue the requests if one is already ongoing, to prevent multiple activations from happening at the same time. This should still work using a promise-based approach, it would only need a central orchestrator function for the request queue.

**Comment by b1ink0** [comment] 2024-11-18 19:10
@mukeshpanchal27 
When activating multiple plugins simultaneously using AJAX a race condition is occurring due to concurrent access and updates to the `active_plugins` option in the database. This race condition is resulting in some plugins not being activated as expected.

The `activate_plugin()` function in WordPress is responsible for activating plugins by updating the `active_plugins` option in the database. It does following steps:
- Retrieve the current list of active plugins.
- Add the new plugin to the list.
- Update the `active_plugins` option with the new list.

Due to the overlapping execution of these requests. The last request to complete overwrites the `active_plugins` option, causing earlier activations to be lost. Only the plugins from the last request appear active, while others remain inactive.

This is the `error_log()` which I added to the `activate_plugin` function in core file `wp-admin/includes/plugin.php` for debugging.

![Image](https://github.com/user-attachments/assets/0f72479d-2198-4011-b1c6-0d42ffe9cb78)

I was able to reproduce this issue I clicked on the `Modern Image Formats` then `Embed Optimizer` then `Web Worker Offloading` fast.

Error log output:
![Image](https://github.com/user-attachments/assets/a2c9dd7a-7b7e-40de-915f-042961a2074e)

Plugins page:
![Image](https://github.com/user-attachments/assets/769afa9f-e477-40b3-a50d-eeecef861e63)

Potential Solutions:
1. Sequential activation using the queue in JavaScript
2. Using `wp_cache_delete( 'alloptions', 'options' );` before calling the `activate_plugin()`
    - I tried this approach and is working.
    ![Image](https://github.com/user-attachments/assets/5e3f3bd4-23d1-4b25-b540-f64f16304474)
    ![Image](https://github.com/user-attachments/assets/0e332267-8df2-4593-8b04-cc03fb49967d)

**Comment by felixarntz** [comment] 2024-11-18 19:23
Thank you for the detailed report @b1ink0.

Regarding clearing of the `alloptions` cache, I wonder how reliable that is. Wouldn't there always be a chance for a race condition if the requests happen at the same time? Meaning: If plugin A and B are being activated at the same time, both AJAX requests would fetch the option before any of them are updated. And then when they update, only the last one would be successful in storing the plugin in the option array.

That's my understanding at least. So from that perspective, I would find a request queue the safer solution.

**Comment by felixarntz** [comment] 2024-11-20 00:33
Fixed via #1675, which will be included in an extra Performance Lab 3.6.1 release, see #1677.

**Closed as completed** 2024-11-20 00:33 UTC
Labels: [Type] Bug, [Plugin] Performance Lab
