### ISSUE TITLE
JavaScript bundling with WP-Scripts and Webpack

### ISSUE THREAD

**Issue by erikyo** [WordPress/performance#467] opened 2022-08-08 19:19 UTC
## Feature Description
We should use wp-script to postprocess js file so that all scripts will be minified and processed by babel... This gives countless benefits among them a smaller file and greater compatibility.
I Noticed also that there is no browserslist. if it is possible i would like to add that as well! 

What do you think? is it an easy addition that would improve the js scripts now and those that will be added in the future

**Comment by mxbclang** [comment] 2022-08-08 22:28
Thanks @erikyo! Tagging @felixarntz in here for his feedback.

**Comment by mxbclang** [comment] 2022-08-08 22:29
Oops @erikyo I just saw that you discussed this with him in #459, so it looks like you already have what you need here! Reassigning to you.

**Comment by erikyo** [comment] 2022-08-08 22:33
thanks to you! and sorry I hadn't linked the original conversation... 😓

**Comment by swissspidy** [comment] 2024-07-26 15:55
Duplicate of #226

**Closed as not planned by swissspidy** 2024-07-26 15:55 UTC
Labels: Infrastructure, [Plugin] Performance Lab
