### ISSUE TITLE
Disable Speculative Loading by default when the user is logged-in or no-cache headers are sent

### ISSUE THREAD

**Issue by westonruter** [WordPress/performance#1709] opened 2024-11-29 23:13 UTC
As first mentioned in https://github.com/WordPress/performance/issues/1692#issuecomment-2507032582, Chrome is going to be [removing the five-minute rule for `<link rel=prefetch>`](https://groups.google.com/a/chromium.org/g/blink-dev/c/Zdo71C0k9C0/m/BRXW6aQiAAAJ). This means Speculative Loading will no longer work on pages when a user is logged-in since in this case WordPress [sends](https://github.com/WordPress/wordpress-develop/blob/4a03ebeffe993d9e61b9339586b67435ce5c0ecf/src/wp-includes/functions.php#L1496C6-L1496C61) a `Cache-Control` response header with `no-cache, must-revalidate, max-age=0, no-store, private`.

Speculative Loading should also be disabled if a page was served with [`nocache_headers()`](https://github.com/WordPress/wordpress-develop/blob/4a03ebeffe993d9e61b9339586b67435ce5c0ecf/src/wp-includes/functions.php#L1520-L1545) having been called.

Without these changes, there is a risk that a site may be attempting to prefetch pages only to have them discarded due to the `Cache-Control` response header. This would needlessly add server load without any user benefit.

A Site Health test for a site unconditionally sending the `nocache_headers()` would also make sense which is captured in #1692. This is relevant not only for Speculative Loading but also for bfcache.

**Comment by westonruter** [comment] 2024-11-29 23:14
cc @felixarntz

**Comment by westonruter** [comment] 2024-12-01 19:34
@tunetheweb has this been on your radar?

**Comment by tunetheweb** [comment] 2024-12-01 19:51
Awaiting 100% confirmation from the Tokyo team but my understanding is this doesn’t affect Speculation Rules.

**Comment by tunetheweb** [comment] 2024-12-04 18:41
Confirmed this will not affect Speculation Rules for the [reasons given here](https://developer.chrome.com/docs/web-platform/prerender-pages#no-cache).

So think we can close this @westonruter ?

**Closed as not planned** 2024-12-04 19:32 UTC
Labels: [Type] Enhancement, [Plugin] Speculative Loading

**Comment by gilbertococchi** [comment] 2025-01-16 13:49
@westonruter I took a stab at looking at the HTTP Archive data and it looks like there are at least 547k WP Origins using CCNS to date.
