### ISSUE TITLE
Performance page plugins cannot deactivated

### ISSUE THREAD

**Issue by jomonthomaslobo** [WordPress/performance#1292] opened 2024-06-10 17:31 UTC
== Bug Report
=== Description
Performance page plugins cannot deactivated

=== Environment
- WordPress: 6.6-beta1
- PHP: 8.2.4
- Server: Apache/2.4.56 (Unix) OpenSSL/1.1.1t PHP/8.2.4 mod_perl/2.0.12 Perl/v5.34.1
- Database: mysqli (Server: 10.4.28-MariaDB / Client: mysqlnd 8.2.4)
- Browser: Chrome 125.0.0.0 (Linux)
- Theme: Twenty Twenty-Four 1.1
- MU-Plugins: None activated
- Plugins: 
  * Image Placeholders 1.1.1
  * Modern Image Formats 2.0.1
  * Optimization Detective 0.3.0
  * Performance Lab 3.2.0
  * WordPress Beta Tester 3.5.5

=== Steps to Reproduce
1. Install Performace Lab Plugin
2. Goto Settings -> Perfomance 
3. Click activate for button of any plugin 
4. After preloaded animation the button gets inactive with Label Active
x. 🐞 Bug occurs.

=== Expected Results
1.  ✅ When the the plugin activation complete the button should change to Deactivate.

=== Actual Results
1.  ❌ Button Became inactive unable to deactivate plugin from the screen.
![Screenshot from 2024-06-10 22-53-22](https://github.com/WordPress/performance/assets/16968704/6c8d8ada-221f-47ff-aca4-39f433be0a92)

**Comment by joemcgill** [comment] 2024-06-10 18:30
Thanks for the report, @jomonthomaslobo. Currently, this is the expected behavior for those feature cards on the performance page and each of the plugins can still be deactivated and deleted using the normal Plugins screen at `wp-admin/plugins.php`.

The purpose of the feature cards on the Performance Settings screen is to help users find and install all of the available feature plugins that are being maintained by the WordPress Performance Team, not to duplicate all of the functionality of the plugin install screen. However, we are currently tracking improvements the onboarding flow in #1032 and making this more clear could be a possible improvement.

Since this really isn't a bug, I'm going to close this issue, but will leave a reference in the Onboarding ticket to see what can be done.

**Closed as completed by joemcgill** 2024-06-10 18:30 UTC
Labels: [Type] Bug
